import java.util.Scanner;

public class CheckException {
    public static int division(int num1, int num2) {
        if (num2 == 0) {
            throw new ArithmeticException("zero");
        }
        return num1 / num2;
    }

    public static void main(String[] args) {
        int[] arr = {10, 11, 15, 0, 25};
        Scanner sc = new Scanner(System.in);
        
        System.out.print("Enter a number: ");
        int n = sc.nextInt();

        for (int i = 0; i < arr.length; i++) {
            try {
                int result = division(n, arr[i]);
                System.out.println(n + " / " + arr[i] + " = " + result);
            } catch (ArithmeticException e) {
                System.out.println("Error " + i + ": " + e.getMessage());
            }
        }

        sc.close();
    }
}
